# Generated by Django 5.2.7 on 2026-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_displaysetting_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopagesetting',
            name='crawl',
            field=models.BooleanField(default=True),
        ),
    ]
