# Generated by Django 5.2.7 on 2026-07-16 11:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_seopagesetting_crawl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaysetting',
            options={'ordering': ('location', 'item_type'), 'verbose_name': 'Display Setting', 'verbose_name_plural': 'Display Settings'},
        ),
        migrations.AlterModelOptions(
            name='seopagesetting',
            options={'ordering': ('page',), 'verbose_name': 'SEO Page Setting', 'verbose_name_plural': 'SEO Page Settings'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('group', 'key'), 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='sitemapsetting',
            options={'ordering': ('page',), 'verbose_name': 'Sitemap Setting', 'verbose_name_plural': 'Sitemap Settings'},
        ),
        migrations.AddField(
            model_name='displaysetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created.'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="displaysetting",
            old_name="limit",
            new_name="display_limit",
        ),
        migrations.RenameField(
            model_name="displaysetting",
            old_name="context",
            new_name="location",
        ),
        migrations.AlterUniqueTogether(
            name='displaysetting',
            unique_together={('location', 'item_type')},
        ),
        migrations.AddField(
            model_name='displaysetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
        migrations.AddField(
            model_name='seopagesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seopagesetting',
            name='robots_override',
            field=models.CharField(blank=True, help_text='Optional custom robots directives (e.g. max-image-preview:large).', max_length=100),
        ),
        migrations.AddField(
            model_name='seopagesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
        migrations.AddField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='group',
            field=models.CharField(choices=[('general', 'General'), ('branding', 'Branding'), ('contact', 'Contact'), ('social', 'Social'), ('seo', 'SEO'), ('analytics', 'Analytics'), ('homepage', 'Homepage'), ('security', 'Security'), ('footer', 'Footer'), ('performance', 'Performance'), ('email', 'Email'), ('api', 'API'), ('other', 'Other')], db_index=True, default='SEO', help_text='Logical group this setting belongs to.', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
        migrations.AddField(
            model_name='sitemapsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemapsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is exposed through the public API.'),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='item_type',
            field=models.CharField(choices=[('projects', 'Projects'), ('creations', 'Creations'), ('experience', 'Experience'), ('skills', 'Skills'), ('qualifications', 'Qualifications'), ('services', 'Services'), ('social_media', 'Social Media')], db_index=True, help_text='Type of content being displayed.', max_length=40),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User responsible for the latest update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='uploaded_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which this record was created or last modified.', null=True),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='crawl',
            field=models.BooleanField(default=True, help_text='Allow search engines to crawl this page. Used by robots.txt generation.'),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links found on this page.'),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='index',
            field=models.BooleanField(default=True, help_text='Allow this page to appear in search results.'),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is exposed through the public API.'),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('project_detail', 'Project Detail'), ('creations', 'Creations'), ('creations_type', 'Creations Type'), ('creation_detail', 'Creation Detail'), ('experience', 'Experience Section'), ('skills', 'Skills Section'), ('qualifications', 'Qualifications Section'), ('services', 'Services Section'), ('sitemap_html', 'HTML Sitemap'), ('not_found', '404 Page')], db_index=True, help_text='Logical page this SEO rule applies to.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User responsible for the latest update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='uploaded_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which this record was created or last modified.', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description shown in the admin panel.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is exposed through the public API.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(db_index=True, help_text='Unique machine-readable setting key.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('boolean', 'Boolean'), ('number', 'Number'), ('color', 'Color')], default='text', help_text='Data type of the stored value.', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User responsible for the latest update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setting',
            name='uploaded_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which this record was created or last modified.', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, help_text='Stored value. Interpretation depends on the selected type.'),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', help_text='Suggested change frequency for search engines.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='include',
            field=models.BooleanField(default=True, help_text='Whether URLs of this page type should appear in sitemap.xml.'),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is exposed through the public API.'),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('project_detail', 'Project Detail'), ('creations', 'Creations'), ('creations_type', 'Creations Type'), ('creation_detail', 'Creation Detail'), ('experience', 'Experience Section'), ('skills', 'Skills Section'), ('qualifications', 'Qualifications Section'), ('services', 'Services Section'), ('sitemap_html', 'HTML Sitemap'), ('not_found', '404 Page')], db_index=True, help_text='Logical page this sitemap rule applies to.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='priority',
            field=models.FloatField(default=0.5, help_text='Sitemap priority (0.0–1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User responsible for the latest update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='uploaded_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which this record was created or last modified.', null=True),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['group'], name='settings_se_group_d01fee_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['key'], name='settings_se_key_4477c8_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['is_public'], name='settings_se_is_publ_811e72_idx'),
        ),
    ]
