# Generated by Django 5.2.7 on 2026-07-16 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_displaysetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysetting',
            name='display_limit',
            field=models.PositiveIntegerField(default=6, help_text='Maximum number of items to display.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='location',
            field=models.CharField(choices=[('home', 'Homepage'), ('project_list', 'Projects Listing'), ('project_detail', 'Project Detail'), ('creations', 'Creations Listing'), ('creations_type', 'Creations Type'), ('creation_detail', 'Creation Detail')], db_index=True, help_text='Where the content is displayed.', max_length=40),
        ),
    ]
