# Generated by Django 5.2.7 on 2026-04-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('goal_type', models.CharField(choices=[('click', 'Button Click'), ('submit', 'Form Submit'), ('download', 'File Download'), ('scroll', 'Scroll Depth'), ('time', 'Time on Page'), ('pageview', 'Page View'), ('external_click', 'External Link Click')], max_length=20)),
                ('target_selector', models.CharField(blank=True, help_text='CSS selector or element ID', max_length=500)),
                ('target_url', models.CharField(blank=True, help_text='URL pattern to match', max_length=500)),
                ('target_value', models.CharField(blank=True, help_text='Minimum scroll % or seconds', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GSCCrawlStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('pages_crawled_per_day', models.PositiveIntegerField(default=0)),
                ('response_2xx', models.PositiveIntegerField(default=0)),
                ('response_3xx', models.PositiveIntegerField(default=0)),
                ('response_4xx', models.PositiveIntegerField(default=0)),
                ('response_5xx', models.PositiveIntegerField(default=0)),
                ('time_spent_ms', models.PositiveIntegerField(default=0)),
                ('kilobytes_downloaded', models.PositiveIntegerField(default=0)),
                ('host', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AEOHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('serp_feature', models.CharField(choices=[('featured_snippet', 'Featured Snippet'), ('people_also_ask', 'People Also Ask'), ('ai_overview', 'AI Overview'), ('knowledge_panel', 'Knowledge Panel'), ('rich_result', 'Rich Result'), ('video_carousel', 'Video Carousel'), ('image_pack', 'Image Pack'), ('top_stories', 'Top Stories')], db_index=True, max_length=30)),
                ('url', models.URLField()),
                ('is_present', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_text', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'keyword', 'serp_feature'],
                'indexes': [models.Index(fields=['serp_feature', '-date'], name='seo_aeohit_serp_fe_1b46e0_idx'), models.Index(fields=['is_present', '-date'], name='seo_aeohit_is_pres_50c031_idx')],
                'unique_together': {('keyword', 'serp_feature', 'url', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True)),
                ('target_url', models.URLField(db_index=True)),
                ('anchor_text', models.CharField(blank=True, max_length=500)),
                ('domain_authority', models.PositiveIntegerField(blank=True, null=True)),
                ('page_authority', models.PositiveIntegerField(blank=True, null=True)),
                ('is_dofollow', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_seen', models.DateField()),
                ('last_checked', models.DateField()),
                ('link_type', models.CharField(choices=[('text', 'Text Link'), ('image', 'Image Link'), ('redirect', 'Redirect'), ('canonical', 'Canonical')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-domain_authority', '-first_seen'],
                'indexes': [models.Index(fields=['target_url', '-domain_authority'], name='seo_backlin_target__aeae92_idx'), models.Index(fields=['is_active', '-last_checked'], name='seo_backlin_is_acti_6548ea_idx')],
                'unique_together': {('source_url', 'target_url')},
            },
        ),
        migrations.CreateModel(
            name='GSCCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('indexed', 'Indexed'), ('excluded', 'Excluded'), ('error', 'Error'), ('warning', 'Warning'), ('submitted', 'Submitted')], db_index=True, max_length=20)),
                ('issue_type', models.CharField(choices=[('no_issue', 'No Issue'), ('not_found', 'Not Found (404)'), ('server_error', 'Server Error (5xx)'), ('redirect_error', 'Redirect Error'), ('blocked_robots', 'Blocked by Robots'), ('duplicate', 'Duplicate without Canonical'), ('soft_404', 'Soft 404'), ('crawl_anomaly', 'Crawl Anomaly')], default='no_issue', max_length=30)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('last_submitted', models.DateTimeField(blank=True, null=True)),
                ('sitemap', models.URLField(blank=True)),
                ('page_fetch_state', models.CharField(blank=True, max_length=50)),
                ('indexing_state', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='seo_gsccove_status_6949ef_idx'), models.Index(fields=['issue_type', '-updated_at'], name='seo_gsccove_issue_t_6aab87_idx')],
            },
        ),
        migrations.CreateModel(
            name='GSCQueryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('page', models.URLField(db_index=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('position', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('country', models.CharField(default='usa', max_length=10)),
                ('device', models.CharField(default='desktop', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['query', '-date'], name='seo_gscquer_query_3a930d_idx'), models.Index(fields=['page', '-date'], name='seo_gscquer_page_8f6c8e_idx')],
                'unique_together': {('query', 'page', 'country', 'device', 'date')},
            },
        ),
        migrations.CreateModel(
            name='KeywordRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('search_engine', models.CharField(choices=[('google', 'Google'), ('bing', 'Bing')], default='google', max_length=50)),
                ('location', models.CharField(default='United States', max_length=100)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('previous_position', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField()),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('keyword_difficulty', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'keyword'],
                'indexes': [models.Index(fields=['keyword', '-date'], name='seo_keyword_keyword_aae647_idx'), models.Index(fields=['url', '-date'], name='seo_keyword_url_510404_idx')],
                'unique_together': {('keyword', 'search_engine', 'location', 'device', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LocalCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_business', 'Google Business Profile'), ('yelp', 'Yelp'), ('bing', 'Bing Places'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('apple_maps', 'Apple Maps'), ('tripadvisor', 'TripAdvisor'), ('other', 'Other')], db_index=True, max_length=30)),
                ('platform_url', models.URLField(blank=True)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('is_consistent', models.BooleanField(db_index=True, default=True)),
                ('inconsistencies', models.JSONField(blank=True, default=dict)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_checked'],
                'unique_together': {('platform', 'business_name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('schema_type', models.CharField(choices=[('Organization', 'Organization'), ('Person', 'Person'), ('HowTo', 'HowTo'), ('Course', 'Course'), ('Event', 'Event'), ('JobPosting', 'Job Posting'), ('Product', 'Product'), ('Review', 'Review'), ('AggregateRating', 'Aggregate Rating'), ('FAQPage', 'FAQ Page'), ('Article', 'Article'), ('BlogPosting', 'Blog Posting'), ('WebSite', 'WebSite'), ('BreadcrumbList', 'Breadcrumb List'), ('SpeakableSpecification', 'Speakable')], db_index=True, max_length=30)),
                ('json_content', models.JSONField()),
                ('is_valid', models.BooleanField(db_index=True, default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['page_path', 'schema_type'],
                'indexes': [models.Index(fields=['schema_type', 'is_valid'], name='seo_schemam_schema__a4754f_idx')],
                'unique_together': {('page_path', 'schema_type')},
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField()),
                ('referrer', models.URLField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seo.conversiongoal')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['goal', '-timestamp'], name='seo_convers_goal_id_52b9ec_idx'), models.Index(fields=['session_id', '-timestamp'], name='seo_convers_session_32fd6a_idx')],
            },
        ),
    ]
