# Generated by Django 5.2.7 on 2026-07-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionevent',
            name='event_type',
            field=models.CharField(db_index=True, default='click', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversionevent',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seo.conversiongoal'),
        ),
    ]
