# Generated by Django 5.2.7 on 2026-07-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_conversionevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICrawlerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler', models.CharField(choices=[('gptbot', 'OpenAI GPTBot'), ('chatgpt_user', 'ChatGPT-User'), ('claudebot', 'Anthropic ClaudeBot'), ('claude_user', 'Claude-User'), ('perplexitybot', 'PerplexityBot'), ('google_extended', 'Google-Extended'), ('bingbot', 'Bingbot'), ('amazonbot', 'Amazonbot'), ('bytespider', 'ByteDance Bytespider'), ('applebot', 'Applebot'), ('other_ai', 'Other AI Crawler')], db_index=True, max_length=30)),
                ('user_agent_raw', models.CharField(max_length=500)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['crawler', '-timestamp'], name='seo_aicrawl_crawler_2df288_idx'), models.Index(fields=['path', '-timestamp'], name='seo_aicrawl_path_8562d2_idx')],
            },
        ),
    ]
