# Generated by Django 5.2.7 on 2026-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_aicrawlervisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicrawlervisit',
            name='canonical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aicrawlervisit',
            name='host',
            field=models.CharField(default='domain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aicrawlervisit',
            name='redirect_reason',
            field=models.CharField(blank=True, choices=[('deployment_host', 'Vercel deployment host'), ('custom_redirect', 'Application redirect'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aicrawlervisit',
            name='redirected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aicrawlervisit',
            name='crawler',
            field=models.CharField(choices=[('gptbot', 'OpenAI GPTBot'), ('chatgpt_user', 'ChatGPT-User'), ('claudebot', 'Anthropic ClaudeBot'), ('claude_user', 'Claude-User'), ('googlebot', 'Googlebot'), ('google_extended', 'Google-Extended'), ('googleother', 'GoogleOther'), ('bingbot', 'Bingbot'), ('perplexitybot', 'PerplexityBot'), ('perplexity_user', 'Perplexity-User'), ('amazonbot', 'Amazonbot'), ('applebot', 'Applebot'), ('bytespider', 'ByteDance Bytespider'), ('ccbot', 'Common Crawl CCBot'), ('yandexbot', 'YandexBot'), ('duckassistbot', 'DuckAssistBot'), ('facebookbot', 'Meta ExternalHit'), ('oai_searchbot', 'OpenAI SearchBot'), ('other_ai', 'Other AI Crawler')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aicrawlervisit',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='aicrawlervisit',
            index=models.Index(fields=['host', '-timestamp'], name='seo_aicrawl_host_67f804_idx'),
        ),
        migrations.AddIndex(
            model_name='aicrawlervisit',
            index=models.Index(fields=['canonical', '-timestamp'], name='seo_aicrawl_canonic_f00ed0_idx'),
        ),
    ]
