# Generated by Django 5.2.7 on 2026-07-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_aicrawlervisit_canonical_aicrawlervisit_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionevent',
            name='url',
        ),
        migrations.RemoveField(
            model_name='conversionevent',
            name='value',
        ),
        migrations.AddField(
            model_name='conversionevent',
            name='event_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversionevent',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversionevent',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversionevent',
            name='path',
            field=models.CharField(db_index=True, default='/', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversionevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('cta_click', 'CTA Click'), ('project_view', 'Project View'), ('scroll', 'Scroll'), ('time', 'Time'), ('form_submit', 'Form Submit'), ('download', 'Download'), ('outbound_link', 'Outbound Link'), ('custom', 'Custom')], db_index=True, help_text='High-level category of the tracked event.', max_length=30),
        ),
        migrations.AlterField(
            model_name='conversionevent',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='seo.conversiongoal'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='seo_convers_event_t_9e6671_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['path', '-timestamp'], name='seo_convers_path_1ee43e_idx'),
        ),
    ]
